name: SentinelSync CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Compilation
        run: javac src/*.java -d .

      - name: Set up Docker Buildx
        uses: actions/setup-qemu-action@v3
        
      - name: Build Docker Image
        run: |
          docker build -t sentinelsync:${{ github.sha }} .